package constants

const (
	WS_SERVER_RESPONSE_SUCCESS = "SUCCESS"
	WS_SERVER_RESPONSE_ERROR   = "ERROR"

	WS_EVENT_INIT_MATCHMAKING = "MATCHMAKING"
	WS_EVENT_EMIT_START_GAME  = "START_GAME"

	WS_ROOM_TYPE_GAME = "GAME"
)
