package constants

const (
	WS_SERVER_RESPONSE_SUCCESS = "SUCCESS"
	WS_SERVER_RESPONSE_ERROR   = "ERROR"

	// GUEST EVENT WILL BEGIN WITH "GUEST:"

	// WS RESP
	WS_EVENT_EMIT_START_GAME             = "START_GAME"
	WS_EVENT_EMIT_UPDATE_GAME_STATE      = "UPDATE_GAME_STATE"
	WS_EVENT_EMIT_END_GAME               = "END_GAME"
	WS_EVENT_EMIT_GET_GAME_TIME_DURATION = "GAME_TIME_DURATION"

	// WS REQ
	WS_EVENT_INIT_MATCHMAKING       = "MATCHMAKING"
	WS_EVENT_CONNECT_GAME           = "CONNECT_GAME"
	WS_EVENT_GAME_PUBLISH_ACTION    = "GAME_PUBLISH_ACTION"
	WS_EVENT_GET_GAME_TIME_DURATION = "GET_GAME_TIME_DURATION"

	WS_ROOM_TYPE_GAME = "GAME"
)
