package constants

const (
	WS_SERVER_RESPONSE_SUCCESS = "SUCCESS"
	WS_SERVER_RESPONSE_ERROR   = "ERROR"

	// GUEST EVENT WILL BEGIN WITH "GUEST:"
	WS_EVENT_INIT_MATCHMAKING = "MATCHMAKING"
	WS_EVENT_EMIT_START_GAME  = "START_GAME"

	WS_EVENT_RESTORE_GAME_CONNECTION = "GAME_CONN_RESTORE"

	WS_ROOM_TYPE_GAME = "GAME"
)
