services:
  psql:
    image: "postgres:16"
    ports:
      - "5432:5432"
    env_file:
    - ./.env
    environment:
      POSTGRES_DB : ${POSTGRES_DB_DATABASE}
      POSTGRES_USER : ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD : ${POSTGRES_DB_PASSWORD}
    restart: always
    volumes:
      - /var/chesshouzs/storage/psql/data:/var/lib/postgresql/data
  redis:
    image: "redis:5.0.8"
    command: redis-server --appendonly yes
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - /var/chesshouzs/storage/redis:/data:rw


# volumes:
#   psql:
#     driver: local
#   redis:
#     driver: local


    